# Generated by Django 6.0.5 on 2026-05-19 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000, unique=True)),
                ('link', models.URLField(max_length=10000)),
                ('source', models.CharField(max_length=200)),
                ('published_date', models.DateTimeField()),
                ('description', models.TextField(blank=True)),
                ('full_text', models.TextField(blank=True)),
                ('summary', models.TextField(blank=True)),
                ('reason', models.TextField(blank=True)),
                ('matched_keywords', models.JSONField(default=list)),
                ('is_relevant', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-published_date'],
                'indexes': [models.Index(fields=['published_date', 'source'], name='newsfeeds_n_publish_e3a00b_idx')],
            },
        ),
    ]
