# Generated by Django 6.0.5 on 2026-05-21 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsfeeds', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticle',
            name='direction',
            field=models.CharField(choices=[('positive', 'Positive'), ('negative', 'Negative'), ('neutral', 'Neutral'), ('pending', 'Pending')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='direction_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='impact_score',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='link',
            field=models.URLField(max_length=1000),
        ),
    ]
