# Generated by Django 6.0.5 on 2026-05-22 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsfeeds', '0002_newsarticle_direction_newsarticle_direction_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticle',
            name='channel',
            field=models.CharField(blank=True, default='News & Media', max_length=200),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='event_class',
            field=models.CharField(blank=True, default='Economic Impact', max_length=200),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='sub_type',
            field=models.CharField(blank=True, default='General News', max_length=200),
        ),
    ]
