# Generated by Django 6.0.5 on 2026-05-22 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsfeeds', '0003_newsarticle_channel_newsarticle_event_class_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticle',
            name='trade_share',
            field=models.TextField(blank=True, default=''),
        ),
    ]
