# Generated by Django 4.2.7 on 2026-05-25 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsfeeds', '0004_newsarticle_trade_share'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticle',
            name='origin',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
