# Generated by Django 6.0.5 on 2026-06-02 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsfeeds', '0006_remove_newsarticle_trade_share'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticle',
            name='sector',
            field=models.CharField(blank=True, default='General / Macro', max_length=200),
        ),
    ]
