# Generated by Django 6.0.5 on 2026-06-04 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsfeeds', '0007_newsarticle_sector'),
    ]

    operations = [
        migrations.CreateModel(
            name='DuplicateNewsArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('link', models.URLField(max_length=1000)),
                ('source', models.CharField(max_length=200)),
                ('published_date', models.DateTimeField()),
                ('description', models.TextField(blank=True)),
                ('full_text', models.TextField(blank=True)),
                ('summary', models.TextField(blank=True)),
                ('reason', models.TextField(blank=True)),
                ('matched_keywords', models.JSONField(default=list)),
                ('is_relevant', models.BooleanField(default=True)),
                ('event_class', models.CharField(blank=True, default='Economic Impact', max_length=200)),
                ('sector', models.CharField(blank=True, default='General / Macro', max_length=200)),
                ('sub_type', models.CharField(blank=True, default='General News', max_length=200)),
                ('channel', models.CharField(blank=True, default='News & Media', max_length=200)),
                ('origin', models.CharField(blank=True, default='', max_length=500)),
                ('direction', models.CharField(choices=[('positive', 'Positive'), ('negative', 'Negative'), ('neutral', 'Neutral'), ('pending', 'Pending')], default='pending', max_length=20)),
                ('direction_reason', models.TextField(blank=True)),
                ('impact_score', models.SmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-published_date'],
                'indexes': [models.Index(fields=['published_date', 'source'], name='newsfeeds_d_publish_6a2129_idx')],
            },
        ),
    ]
