# Generated by Django 6.0.5 on 2026-06-04 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsfeeds', '0008_duplicatenewsarticle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsarticle',
            name='title',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterUniqueTogether(
            name='newsarticle',
            unique_together={('title', 'link', 'published_date')},
        ),
    ]
