# Generated by Django 6.0.5 on 2026-06-11 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsfeeds', '0009_alter_newsarticle_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='duplicatenewsarticle',
            name='is_channel_mapped',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='duplicatenewsarticle',
            name='is_scraped',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='is_channel_mapped',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='is_scraped',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='link',
            field=models.URLField(max_length=3000),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='title',
            field=models.CharField(max_length=3000),
        ),
    ]
